// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (user_id, scope, scope_id, order_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, scope, scope_id) DO UPDATE
  SET revoked_at = NULL
RETURNING id, user_id, scope, scope_id, order_id, activated_at, revoked_at
`

type CreateEnrollmentParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Scope   string      `json:"scope"`
	ScopeID uuid.UUID   `json:"scope_id"`
	OrderID pgtype.UUID `json:"order_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.UserID,
		arg.Scope,
		arg.ScopeID,
		arg.OrderID,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.OrderID,
		&i.ActivatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const hasCourseAccess = `-- name: HasCourseAccess :one
SELECT EXISTS (
  SELECT 1
  FROM enrollments e
  WHERE e.user_id = $1
    AND e.revoked_at IS NULL
    AND (
      (e.scope = 'course' AND e.scope_id = $2)
      OR (
        e.scope = 'career'
        AND EXISTS (
          SELECT 1 FROM career_courses cc
          WHERE cc.career_id = e.scope_id
            AND cc.course_id = $2
        )
      )
    )
) AS has_access
`

type HasCourseAccessParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ScopeID uuid.UUID `json:"scope_id"`
}

// Acceso a un curso: enrollment directo al curso, o enrollment a una
// carrera que hoy contenga el curso. Los enrollments revocados no cuentan.
func (q *Queries) HasCourseAccess(ctx context.Context, arg HasCourseAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCourseAccess, arg.UserID, arg.ScopeID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const hasLessonAccess = `-- name: HasLessonAccess :one
SELECT
  l.is_free_sample
  OR EXISTS (
    SELECT 1
    FROM enrollments e
    WHERE e.user_id = $1
      AND e.revoked_at IS NULL
      AND (
        (e.scope = 'course' AND e.scope_id = m.course_id)
        OR (
          e.scope = 'career'
          AND EXISTS (
            SELECT 1 FROM career_courses cc
            WHERE cc.career_id = e.scope_id
              AND cc.course_id = m.course_id
          )
        )
      )
  ) AS has_access
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE l.id = $2
`

type HasLessonAccessParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

// Una lección es accesible si es muestra gratis o si el usuario
// tiene acceso al curso que la contiene.
func (q *Queries) HasLessonAccess(ctx context.Context, arg HasLessonAccessParams) (*bool, error) {
	row := q.db.QueryRow(ctx, hasLessonAccess, arg.UserID, arg.ID)
	var has_access *bool
	err := row.Scan(&has_access)
	return has_access, err
}

const listUserEnrollments = `-- name: ListUserEnrollments :many
SELECT id, user_id, scope, scope_id, order_id, activated_at, revoked_at FROM enrollments
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY activated_at DESC
`

func (q *Queries) ListUserEnrollments(ctx context.Context, userID uuid.UUID) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listUserEnrollments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ScopeID,
			&i.OrderID,
			&i.ActivatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEnrollment = `-- name: RevokeEnrollment :one
UPDATE enrollments
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
RETURNING id, user_id, scope, scope_id, order_id, activated_at, revoked_at
`

// Reembolso o baja administrativa. Idempotente: revocar dos veces no
// mueve la fecha original.
func (q *Queries) RevokeEnrollment(ctx context.Context, id uuid.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, revokeEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.OrderID,
		&i.ActivatedAt,
		&i.RevokedAt,
	)
	return i, err
}
