// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetCourseCurriculum = `-- name: AdminGetCourseCurriculum :many
SELECT
  m.id           AS module_id,
  m.title        AS module_title,
  m.position     AS module_position,
  l.id           AS lesson_id,
  l.title        AS lesson_title,
  l.description,
  l.duration_s,
  l.is_free_sample,
  l.position     AS lesson_position,
  l.video_status,
  l.kind,
  l.body_md
FROM modules m
LEFT JOIN lessons l ON l.module_id = m.id
WHERE m.course_id = $1
ORDER BY m.position, l.position
`

type AdminGetCourseCurriculumRow struct {
	ModuleID       uuid.UUID   `json:"module_id"`
	ModuleTitle    string      `json:"module_title"`
	ModulePosition int32       `json:"module_position"`
	LessonID       pgtype.UUID `json:"lesson_id"`
	LessonTitle    *string     `json:"lesson_title"`
	Description    *string     `json:"description"`
	DurationS      *int32      `json:"duration_s"`
	IsFreeSample   *bool       `json:"is_free_sample"`
	LessonPosition *int32      `json:"lesson_position"`
	VideoStatus    *string     `json:"video_status"`
	Kind           *string     `json:"kind"`
	BodyMd         *string     `json:"body_md"`
}

// Como GetCourseCurriculum pero con módulos vacíos y estado del video.
// video_asset_id sigue sin salir: el admin opera por estado.
func (q *Queries) AdminGetCourseCurriculum(ctx context.Context, courseID uuid.UUID) ([]AdminGetCourseCurriculumRow, error) {
	rows, err := q.db.Query(ctx, adminGetCourseCurriculum, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetCourseCurriculumRow
	for rows.Next() {
		var i AdminGetCourseCurriculumRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.ModuleTitle,
			&i.ModulePosition,
			&i.LessonID,
			&i.LessonTitle,
			&i.Description,
			&i.DurationS,
			&i.IsFreeSample,
			&i.LessonPosition,
			&i.VideoStatus,
			&i.Kind,
			&i.BodyMd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCareers = `-- name: AdminListCareers :many


SELECT c.id, c.slug, c.title, c.subtitle, c.description, c.level, c.price_cents, c.status, c.position, c.created_at, c.updated_at, (SELECT count(*) FROM career_courses cc WHERE cc.career_id = c.id)::int AS course_count
FROM careers c
ORDER BY c.position, c.created_at
`

type AdminListCareersRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Subtitle    string             `json:"subtitle"`
	Description string             `json:"description"`
	Level       string             `json:"level"`
	PriceCents  int32              `json:"price_cents"`
	Status      string             `json:"status"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CourseCount int32              `json:"course_count"`
}

// Queries de administración (P7). Solo las usa el rol admin.
// ---------------------------------------------------------------------------
// Carreras
// ---------------------------------------------------------------------------
func (q *Queries) AdminListCareers(ctx context.Context) ([]AdminListCareersRow, error) {
	rows, err := q.db.Query(ctx, adminListCareers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCareersRow
	for rows.Next() {
		var i AdminListCareersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCourses = `-- name: AdminListCourses :many

SELECT c.id, c.slug, c.title, c.subtitle, c.description, c.level, c.price_cents, c.status, c.position, c.created_at, c.updated_at,
  (SELECT count(*) FROM modules m JOIN lessons l ON l.module_id = m.id WHERE m.course_id = c.id)::int AS lesson_count
FROM courses c
ORDER BY c.position, c.created_at
`

type AdminListCoursesRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Subtitle    string             `json:"subtitle"`
	Description string             `json:"description"`
	Level       string             `json:"level"`
	PriceCents  int32              `json:"price_cents"`
	Status      string             `json:"status"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LessonCount int32              `json:"lesson_count"`
}

// ---------------------------------------------------------------------------
// Cursos
// ---------------------------------------------------------------------------
func (q *Queries) AdminListCourses(ctx context.Context) ([]AdminListCoursesRow, error) {
	rows, err := q.db.Query(ctx, adminListCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCoursesRow
	for rows.Next() {
		var i AdminListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserEnrollments = `-- name: AdminListUserEnrollments :many
SELECT e.id, e.user_id, e.scope, e.scope_id, e.order_id, e.activated_at, e.revoked_at,
  COALESCE(c.title, k.title, '') AS product_title,
  COALESCE(c.slug, k.slug, '')   AS product_slug
FROM enrollments e
LEFT JOIN courses c ON e.scope = 'course' AND c.id = e.scope_id
LEFT JOIN careers k ON e.scope = 'career' AND k.id = e.scope_id
WHERE e.user_id = $1
ORDER BY e.activated_at DESC
`

type AdminListUserEnrollmentsRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Scope        string             `json:"scope"`
	ScopeID      uuid.UUID          `json:"scope_id"`
	OrderID      pgtype.UUID        `json:"order_id"`
	ActivatedAt  pgtype.Timestamptz `json:"activated_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	ProductTitle string             `json:"product_title"`
	ProductSlug  string             `json:"product_slug"`
}

func (q *Queries) AdminListUserEnrollments(ctx context.Context, userID uuid.UUID) ([]AdminListUserEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserEnrollments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUserEnrollmentsRow
	for rows.Next() {
		var i AdminListUserEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ScopeID,
			&i.OrderID,
			&i.ActivatedAt,
			&i.RevokedAt,
			&i.ProductTitle,
			&i.ProductSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT u.id, u.email, u.name, u.role, u.created_at,
  (SELECT count(*) FROM enrollments e WHERE e.user_id = u.id AND e.revoked_at IS NULL)::int AS active_enrollments
FROM users u
WHERE $3::text = '' OR u.email ILIKE '%' || $3::text || '%' OR u.name ILIKE '%' || $3::text || '%'
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Q      string `json:"q"`
}

type AdminListUsersRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	Name              string             `json:"name"`
	Role              string             `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ActiveEnrollments int32              `json:"active_enrollments"`
}

// ---------------------------------------------------------------------------
// Alumnos
// ---------------------------------------------------------------------------
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.ActiveEnrollments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCareer = `-- name: CreateCareer :one
INSERT INTO careers (slug, title, subtitle, description, level, price_cents, status, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, (SELECT COALESCE(MAX(position), 0) + 1 FROM careers))
RETURNING id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at
`

type CreateCareerParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	Level       string `json:"level"`
	PriceCents  int32  `json:"price_cents"`
	Status      string `json:"status"`
}

func (q *Queries) CreateCareer(ctx context.Context, arg CreateCareerParams) (Career, error) {
	row := q.db.QueryRow(ctx, createCareer,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.PriceCents,
		arg.Status,
	)
	var i Career
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (slug, title, subtitle, description, level, price_cents, status, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, (SELECT COALESCE(MAX(position), 0) + 1 FROM courses))
RETURNING id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at
`

type CreateCourseParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	Level       string `json:"level"`
	PriceCents  int32  `json:"price_cents"`
	Status      string `json:"status"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.PriceCents,
		arg.Status,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (module_id, title, description, duration_s, is_free_sample, kind, body_md, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, (SELECT COALESCE(MAX(position), 0) + 1 FROM lessons WHERE module_id = $1))
RETURNING id, module_id, title, description, video_provider, video_asset_id, video_status, duration_s, is_free_sample, position, created_at, updated_at, kind, body_md
`

type CreateLessonParams struct {
	ModuleID     uuid.UUID `json:"module_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	DurationS    int32     `json:"duration_s"`
	IsFreeSample bool      `json:"is_free_sample"`
	Kind         string    `json:"kind"`
	BodyMd       string    `json:"body_md"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ModuleID,
		arg.Title,
		arg.Description,
		arg.DurationS,
		arg.IsFreeSample,
		arg.Kind,
		arg.BodyMd,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one

INSERT INTO modules (course_id, title, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position), 0) + 1 FROM modules WHERE course_id = $1))
RETURNING id, course_id, title, position, created_at, updated_at
`

type CreateModuleParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Title    string    `json:"title"`
}

// ---------------------------------------------------------------------------
// Módulos y lecciones
// ---------------------------------------------------------------------------
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule, arg.CourseID, arg.Title)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCareer = `-- name: DeleteCareer :exec
DELETE FROM careers WHERE id = $1
`

func (q *Queries) DeleteCareer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCareer, id)
	return err
}

const deleteCareerCourses = `-- name: DeleteCareerCourses :exec
DELETE FROM career_courses WHERE career_id = $1
`

func (q *Queries) DeleteCareerCourses(ctx context.Context, careerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCareerCourses, careerID)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModule, id)
	return err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, user_id, scope, scope_id, order_id, activated_at, revoked_at FROM enrollments WHERE id = $1
`

func (q *Queries) GetEnrollment(ctx context.Context, id uuid.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.OrderID,
		&i.ActivatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, course_id, title, position, created_at, updated_at FROM modules WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCareerCourse = `-- name: InsertCareerCourse :exec
INSERT INTO career_courses (career_id, course_id, position) VALUES ($1, $2, $3)
`

type InsertCareerCourseParams struct {
	CareerID uuid.UUID `json:"career_id"`
	CourseID uuid.UUID `json:"course_id"`
	Position int32     `json:"position"`
}

func (q *Queries) InsertCareerCourse(ctx context.Context, arg InsertCareerCourseParams) error {
	_, err := q.db.Exec(ctx, insertCareerCourse, arg.CareerID, arg.CourseID, arg.Position)
	return err
}

const listLessonIDs = `-- name: ListLessonIDs :many
SELECT id FROM lessons WHERE module_id = $1 ORDER BY position
`

func (q *Queries) ListLessonIDs(ctx context.Context, moduleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLessonIDs, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleIDs = `-- name: ListModuleIDs :many
SELECT id FROM modules WHERE course_id = $1 ORDER BY position
`

func (q *Queries) ListModuleIDs(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listModuleIDs, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLessonKind = `-- name: SetLessonKind :one
UPDATE lessons
SET kind = $2, body_md = CASE WHEN $2 = 'video' THEN '' ELSE body_md END
WHERE id = $1 AND video_status = 'none'
RETURNING id, module_id, title, description, video_provider, video_asset_id, video_status, duration_s, is_free_sample, position, created_at, updated_at, kind, body_md
`

type SetLessonKindParams struct {
	ID   uuid.UUID `json:"id"`
	Kind string    `json:"kind"`
}

// Cambiar el tipo solo si la lección no tiene video subido; si no,
// no afecta filas y el service devuelve un error accionable.
func (q *Queries) SetLessonKind(ctx context.Context, arg SetLessonKindParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, setLessonKind, arg.ID, arg.Kind)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
	)
	return i, err
}

const setLessonPosition = `-- name: SetLessonPosition :exec
UPDATE lessons SET position = $2 WHERE id = $1
`

type SetLessonPositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetLessonPosition(ctx context.Context, arg SetLessonPositionParams) error {
	_, err := q.db.Exec(ctx, setLessonPosition, arg.ID, arg.Position)
	return err
}

const setModulePosition = `-- name: SetModulePosition :exec
UPDATE modules SET position = $2 WHERE id = $1
`

type SetModulePositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

// Solo dentro de una transacción: UNIQUE (course_id, position) es
// DEFERRABLE INITIALLY DEFERRED justamente para reordenar.
func (q *Queries) SetModulePosition(ctx context.Context, arg SetModulePositionParams) error {
	_, err := q.db.Exec(ctx, setModulePosition, arg.ID, arg.Position)
	return err
}

const updateCareer = `-- name: UpdateCareer :one
UPDATE careers
SET slug = $2, title = $3, subtitle = $4, description = $5, level = $6, price_cents = $7, status = $8
WHERE id = $1
RETURNING id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at
`

type UpdateCareerParams struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Subtitle    string    `json:"subtitle"`
	Description string    `json:"description"`
	Level       string    `json:"level"`
	PriceCents  int32     `json:"price_cents"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateCareer(ctx context.Context, arg UpdateCareerParams) (Career, error) {
	row := q.db.QueryRow(ctx, updateCareer,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.PriceCents,
		arg.Status,
	)
	var i Career
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET slug = $2, title = $3, subtitle = $4, description = $5, level = $6, price_cents = $7, status = $8
WHERE id = $1
RETURNING id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at
`

type UpdateCourseParams struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Subtitle    string    `json:"subtitle"`
	Description string    `json:"description"`
	Level       string    `json:"level"`
	PriceCents  int32     `json:"price_cents"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.PriceCents,
		arg.Status,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = $2, description = $3, duration_s = $4, is_free_sample = $5, body_md = $6
WHERE id = $1
RETURNING id, module_id, title, description, video_provider, video_asset_id, video_status, duration_s, is_free_sample, position, created_at, updated_at, kind, body_md
`

type UpdateLessonParams struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	DurationS    int32     `json:"duration_s"`
	IsFreeSample bool      `json:"is_free_sample"`
	BodyMd       string    `json:"body_md"`
}

// El tipo no se cambia acá: tiene su propia query con guarda.
func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DurationS,
		arg.IsFreeSample,
		arg.BodyMd,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
	)
	return i, err
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules SET title = $2 WHERE id = $1 RETURNING id, course_id, title, position, created_at, updated_at
`

type UpdateModuleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule, arg.ID, arg.Title)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
