// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCareerBySlug = `-- name: GetCareerBySlug :one
SELECT id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at, category_id FROM careers WHERE slug = $1
`

func (q *Queries) GetCareerBySlug(ctx context.Context, slug string) (Career, error) {
	row := q.db.QueryRow(ctx, getCareerBySlug, slug)
	var i Career
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at, category_id FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.PriceCents,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getCourseCurriculum = `-- name: GetCourseCurriculum :many
SELECT
  m.id         AS module_id,
  m.title      AS module_title,
  m.position   AS module_position,
  l.id         AS lesson_id,
  l.title      AS lesson_title,
  l.description,
  l.duration_s,
  l.is_free_sample,
  l.kind,
  l.position   AS lesson_position
FROM modules m
JOIN lessons l ON l.module_id = m.id
WHERE m.course_id = $1
ORDER BY m.position, l.position
`

type GetCourseCurriculumRow struct {
	ModuleID       uuid.UUID `json:"module_id"`
	ModuleTitle    string    `json:"module_title"`
	ModulePosition int32     `json:"module_position"`
	LessonID       uuid.UUID `json:"lesson_id"`
	LessonTitle    string    `json:"lesson_title"`
	Description    string    `json:"description"`
	DurationS      int32     `json:"duration_s"`
	IsFreeSample   bool      `json:"is_free_sample"`
	Kind           string    `json:"kind"`
	LessonPosition int32     `json:"lesson_position"`
}

// Currícula completa de un curso: módulos y lecciones ordenados.
// video_asset_id NO se expone acá: las URLs de reproducción se firman
// por lección en el módulo media, tras verificar acceso.
func (q *Queries) GetCourseCurriculum(ctx context.Context, courseID uuid.UUID) ([]GetCourseCurriculumRow, error) {
	rows, err := q.db.Query(ctx, getCourseCurriculum, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseCurriculumRow
	for rows.Next() {
		var i GetCourseCurriculumRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.ModuleTitle,
			&i.ModulePosition,
			&i.LessonID,
			&i.LessonTitle,
			&i.Description,
			&i.DurationS,
			&i.IsFreeSample,
			&i.Kind,
			&i.LessonPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareerCourses = `-- name: ListCareerCourses :many
SELECT c.id, c.slug, c.title, c.subtitle, c.description, c.level, c.price_cents, c.status, c.position, c.created_at, c.updated_at, c.category_id, cc.position AS career_position
FROM career_courses cc
JOIN courses c ON c.id = cc.course_id
WHERE cc.career_id = $1
ORDER BY cc.position
`

type ListCareerCoursesRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Subtitle       string             `json:"subtitle"`
	Description    string             `json:"description"`
	Level          string             `json:"level"`
	PriceCents     int32              `json:"price_cents"`
	Status         string             `json:"status"`
	Position       int32              `json:"position"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CareerPosition int32              `json:"career_position"`
}

func (q *Queries) ListCareerCourses(ctx context.Context, careerID uuid.UUID) ([]ListCareerCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCareerCourses, careerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCareerCoursesRow
	for rows.Next() {
		var i ListCareerCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CareerPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseStats = `-- name: ListCourseStats :many
SELECT
  m.course_id,
  COUNT(l.id)::int                 AS lesson_count,
  COALESCE(SUM(l.duration_s), 0)::int AS duration_s
FROM modules m
JOIN lessons l ON l.module_id = m.id
GROUP BY m.course_id
`

type ListCourseStatsRow struct {
	CourseID    uuid.UUID `json:"course_id"`
	LessonCount int32     `json:"lesson_count"`
	DurationS   int32     `json:"duration_s"`
}

// Agregados por curso para cards y heros: cantidad de lecciones y
// duración total. Se calcula sobre la currícula (no sobre progreso).
func (q *Queries) ListCourseStats(ctx context.Context) ([]ListCourseStatsRow, error) {
	rows, err := q.db.Query(ctx, listCourseStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseStatsRow
	for rows.Next() {
		var i ListCourseStatsRow
		if err := rows.Scan(&i.CourseID, &i.LessonCount, &i.DurationS); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCareers = `-- name: ListPublishedCareers :many
SELECT id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at, category_id FROM careers
WHERE status = 'published'
ORDER BY position, created_at
`

func (q *Queries) ListPublishedCareers(ctx context.Context) ([]Career, error) {
	rows, err := q.db.Query(ctx, listPublishedCareers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Career
	for rows.Next() {
		var i Career
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCareersForCourse = `-- name: ListPublishedCareersForCourse :many
SELECT c.id, c.slug, c.title, c.subtitle, c.description, c.level, c.price_cents, c.status, c.position, c.created_at, c.updated_at, c.category_id
FROM career_courses cc
JOIN careers c ON c.id = cc.career_id
WHERE cc.course_id = $1 AND c.status = 'published'
ORDER BY c.position, c.created_at
`

// Carreras publicadas que contienen el curso (para el upsell al bundle).
func (q *Queries) ListPublishedCareersForCourse(ctx context.Context, courseID uuid.UUID) ([]Career, error) {
	rows, err := q.db.Query(ctx, listPublishedCareersForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Career
	for rows.Next() {
		var i Career
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT id, slug, title, subtitle, description, level, price_cents, status, position, created_at, updated_at, category_id FROM courses
WHERE status = 'published'
ORDER BY position, created_at
`

func (q *Queries) ListPublishedCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.PriceCents,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
