// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, position, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, position, created_at, updated_at FROM categories ORDER BY position, name
`

// Tabla chica: el service la trae entera y mapea por id.
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCareerCategory = `-- name: SetCareerCategory :exec
UPDATE careers SET category_id = $2 WHERE id = $1
`

type SetCareerCategoryParams struct {
	ID         uuid.UUID   `json:"id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) SetCareerCategory(ctx context.Context, arg SetCareerCategoryParams) error {
	_, err := q.db.Exec(ctx, setCareerCategory, arg.ID, arg.CategoryID)
	return err
}

const setCourseCategory = `-- name: SetCourseCategory :exec
UPDATE courses SET category_id = $2 WHERE id = $1
`

type SetCourseCategoryParams struct {
	ID         uuid.UUID   `json:"id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) SetCourseCategory(ctx context.Context, arg SetCourseCategoryParams) error {
	_, err := q.db.Exec(ctx, setCourseCategory, arg.ID, arg.CategoryID)
	return err
}
