// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demos.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDemo = `-- name: CreateDemo :one
INSERT INTO demos (course_id, slug, title, html, height_px)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, slug, title, html, height_px, created_at, updated_at
`

type CreateDemoParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
	Title    string    `json:"title"`
	Html     string    `json:"html"`
	HeightPx int32     `json:"height_px"`
}

func (q *Queries) CreateDemo(ctx context.Context, arg CreateDemoParams) (Demo, error) {
	row := q.db.QueryRow(ctx, createDemo,
		arg.CourseID,
		arg.Slug,
		arg.Title,
		arg.Html,
		arg.HeightPx,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Slug,
		&i.Title,
		&i.Html,
		&i.HeightPx,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDemo = `-- name: DeleteDemo :exec
DELETE FROM demos WHERE id = $1
`

func (q *Queries) DeleteDemo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDemo, id)
	return err
}

const getDemo = `-- name: GetDemo :one
SELECT id, course_id, slug, title, html, height_px, created_at, updated_at FROM demos WHERE id = $1
`

func (q *Queries) GetDemo(ctx context.Context, id uuid.UUID) (Demo, error) {
	row := q.db.QueryRow(ctx, getDemo, id)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Slug,
		&i.Title,
		&i.Html,
		&i.HeightPx,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDemosByCourse = `-- name: ListDemosByCourse :many
SELECT id, course_id, slug, title, height_px, length(html)::int AS size_bytes, created_at, updated_at
FROM demos
WHERE course_id = $1
ORDER BY title
`

type ListDemosByCourseRow struct {
	ID        uuid.UUID          `json:"id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	HeightPx  int32              `json:"height_px"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Biblioteca de demos de un curso. Sin el HTML: es pesado y solo lo
// necesita el frame firmado o el editor de una demo puntual.
func (q *Queries) ListDemosByCourse(ctx context.Context, courseID uuid.UUID) ([]ListDemosByCourseRow, error) {
	rows, err := q.db.Query(ctx, listDemosByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDemosByCourseRow
	for rows.Next() {
		var i ListDemosByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Slug,
			&i.Title,
			&i.HeightPx,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDemosBySlugs = `-- name: ListDemosBySlugs :many
SELECT id, course_id, slug, title, height_px
FROM demos
WHERE course_id = $1 AND slug = ANY($2::text[])
`

type ListDemosBySlugsParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slugs    []string  `json:"slugs"`
}

type ListDemosBySlugsRow struct {
	ID       uuid.UUID `json:"id"`
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
	Title    string    `json:"title"`
	HeightPx int32     `json:"height_px"`
}

// Las demos referenciadas por un artículo, resueltas dentro del curso.
func (q *Queries) ListDemosBySlugs(ctx context.Context, arg ListDemosBySlugsParams) ([]ListDemosBySlugsRow, error) {
	rows, err := q.db.Query(ctx, listDemosBySlugs, arg.CourseID, arg.Slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDemosBySlugsRow
	for rows.Next() {
		var i ListDemosBySlugsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Slug,
			&i.Title,
			&i.HeightPx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsUsingDemo = `-- name: ListLessonsUsingDemo :many
SELECT l.id, l.title, m.title AS module_title
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1
  AND l.body_md ~ ('(^|\n)[[:space:]]*::demo\[' || $2::text || '\][[:space:]]*(\n|$)')
ORDER BY m.position, l.position
`

type ListLessonsUsingDemoParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
}

type ListLessonsUsingDemoRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	ModuleTitle string    `json:"module_title"`
}

// Lecciones del curso cuyo cuerpo referencia ::demo[slug]. Se usa para
// avisar antes de borrar una demo en uso.
func (q *Queries) ListLessonsUsingDemo(ctx context.Context, arg ListLessonsUsingDemoParams) ([]ListLessonsUsingDemoRow, error) {
	rows, err := q.db.Query(ctx, listLessonsUsingDemo, arg.CourseID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonsUsingDemoRow
	for rows.Next() {
		var i ListLessonsUsingDemoRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ModuleTitle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDemo = `-- name: UpdateDemo :one
UPDATE demos
SET slug = $2, title = $3, html = $4, height_px = $5
WHERE id = $1
RETURNING id, course_id, slug, title, html, height_px, created_at, updated_at
`

type UpdateDemoParams struct {
	ID       uuid.UUID `json:"id"`
	Slug     string    `json:"slug"`
	Title    string    `json:"title"`
	Html     string    `json:"html"`
	HeightPx int32     `json:"height_px"`
}

func (q *Queries) UpdateDemo(ctx context.Context, arg UpdateDemoParams) (Demo, error) {
	row := q.db.QueryRow(ctx, updateDemo,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Html,
		arg.HeightPx,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Slug,
		&i.Title,
		&i.Html,
		&i.HeightPx,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
