// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLesson = `-- name: GetLesson :one
SELECT
  l.id, l.module_id, l.title, l.description, l.video_provider, l.video_asset_id, l.video_status, l.duration_s, l.is_free_sample, l.position, l.created_at, l.updated_at, l.kind, l.body_md,
  m.course_id,
  m.title    AS module_title,
  m.position AS module_position
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE l.id = $1
`

type GetLessonRow struct {
	ID             uuid.UUID          `json:"id"`
	ModuleID       uuid.UUID          `json:"module_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	VideoProvider  string             `json:"video_provider"`
	VideoAssetID   *string            `json:"video_asset_id"`
	VideoStatus    string             `json:"video_status"`
	DurationS      int32              `json:"duration_s"`
	IsFreeSample   bool               `json:"is_free_sample"`
	Position       int32              `json:"position"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Kind           string             `json:"kind"`
	BodyMd         string             `json:"body_md"`
	CourseID       uuid.UUID          `json:"course_id"`
	ModuleTitle    string             `json:"module_title"`
	ModulePosition int32              `json:"module_position"`
}

// Lección con su contexto de curso. Uso interno (media, progress):
// los handlers públicos nunca serializan esta fila directo.
func (q *Queries) GetLesson(ctx context.Context, id uuid.UUID) (GetLessonRow, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
		&i.CourseID,
		&i.ModuleTitle,
		&i.ModulePosition,
	)
	return i, err
}

const setLessonVideoUploading = `-- name: SetLessonVideoUploading :one
UPDATE lessons
SET video_provider = $2,
    video_asset_id = $3,
    video_status   = 'uploading',
    duration_s     = 0
WHERE id = $1
RETURNING id, module_id, title, description, video_provider, video_asset_id, video_status, duration_s, is_free_sample, position, created_at, updated_at, kind, body_md
`

type SetLessonVideoUploadingParams struct {
	ID            uuid.UUID `json:"id"`
	VideoProvider string    `json:"video_provider"`
	VideoAssetID  *string   `json:"video_asset_id"`
}

// Se llama al iniciar un upload: asocia el asset externo y resetea
// la duración (la trae el webhook de transcodificación).
func (q *Queries) SetLessonVideoUploading(ctx context.Context, arg SetLessonVideoUploadingParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, setLessonVideoUploading, arg.ID, arg.VideoProvider, arg.VideoAssetID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
	)
	return i, err
}

const updateLessonVideoByAsset = `-- name: UpdateLessonVideoByAsset :one
UPDATE lessons
SET video_status = $3,
    duration_s   = CASE WHEN $4::int > 0 THEN $4::int ELSE duration_s END
WHERE video_provider = $1 AND video_asset_id = $2
RETURNING id, module_id, title, description, video_provider, video_asset_id, video_status, duration_s, is_free_sample, position, created_at, updated_at, kind, body_md
`

type UpdateLessonVideoByAssetParams struct {
	VideoProvider string  `json:"video_provider"`
	VideoAssetID  *string `json:"video_asset_id"`
	VideoStatus   string  `json:"video_status"`
	Column4       int32   `json:"column_4"`
}

// Transición de estado disparada por webhook o sync manual. Si el
// provider ya informa duración (> 0) se persiste; si no, se conserva.
func (q *Queries) UpdateLessonVideoByAsset(ctx context.Context, arg UpdateLessonVideoByAssetParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLessonVideoByAsset,
		arg.VideoProvider,
		arg.VideoAssetID,
		arg.VideoStatus,
		arg.Column4,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.VideoProvider,
		&i.VideoAssetID,
		&i.VideoStatus,
		&i.DurationS,
		&i.IsFreeSample,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.BodyMd,
	)
	return i, err
}
