// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	Provider   string             `json:"provider"`
	ProviderID string             `json:"provider_id"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Career struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Subtitle    string             `json:"subtitle"`
	Description string             `json:"description"`
	Level       string             `json:"level"`
	PriceCents  int32              `json:"price_cents"`
	Status      string             `json:"status"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CareerCourse struct {
	CareerID uuid.UUID `json:"career_id"`
	CourseID uuid.UUID `json:"course_id"`
	Position int32     `json:"position"`
}

type Course struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Subtitle    string             `json:"subtitle"`
	Description string             `json:"description"`
	Level       string             `json:"level"`
	PriceCents  int32              `json:"price_cents"`
	Status      string             `json:"status"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CourseProgress struct {
	UserID           uuid.UUID          `json:"user_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	CompletedLessons int32              `json:"completed_lessons"`
	TotalLessons     int32              `json:"total_lessons"`
	LastLessonID     pgtype.UUID        `json:"last_lesson_id"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DailyActivity struct {
	UserID  uuid.UUID   `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Seconds int32       `json:"seconds"`
}

type Demo struct {
	ID        uuid.UUID          `json:"id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	Html      string             `json:"html"`
	HeightPx  int32              `json:"height_px"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Scope       string             `json:"scope"`
	ScopeID     uuid.UUID          `json:"scope_id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type Lesson struct {
	ID            uuid.UUID          `json:"id"`
	ModuleID      uuid.UUID          `json:"module_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	VideoProvider string             `json:"video_provider"`
	VideoAssetID  *string            `json:"video_asset_id"`
	VideoStatus   string             `json:"video_status"`
	DurationS     int32              `json:"duration_s"`
	IsFreeSample  bool               `json:"is_free_sample"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Kind          string             `json:"kind"`
	BodyMd        string             `json:"body_md"`
}

type LessonProgress struct {
	UserID      uuid.UUID          `json:"user_id"`
	LessonID    uuid.UUID          `json:"lesson_id"`
	Seconds     int32              `json:"seconds"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Module struct {
	ID        uuid.UUID          `json:"id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Title     string             `json:"title"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	ProductType       string             `json:"product_type"`
	ProductID         uuid.UUID          `json:"product_id"`
	AmountCents       int32              `json:"amount_cents"`
	Currency          string             `json:"currency"`
	Provider          string             `json:"provider"`
	ProviderPaymentID *string            `json:"provider_payment_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
