// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const approveOrderByProviderPayment = `-- name: ApproveOrderByProviderPayment :one
UPDATE orders
SET status = 'approved'
WHERE provider = $1
  AND provider_payment_id = $2
  AND status = 'pending'
RETURNING id, user_id, product_type, product_id, amount_cents, currency, provider, provider_payment_id, status, created_at, updated_at
`

type ApproveOrderByProviderPaymentParams struct {
	Provider          string  `json:"provider"`
	ProviderPaymentID *string `json:"provider_payment_id"`
}

// Punto de idempotencia del webhook: si ya está approved, el UPDATE
// no cambia nada y el handler corta ahí (no re-crea enrollments).
func (q *Queries) ApproveOrderByProviderPayment(ctx context.Context, arg ApproveOrderByProviderPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, approveOrderByProviderPayment, arg.Provider, arg.ProviderPaymentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductType,
		&i.ProductID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attachProviderPayment = `-- name: AttachProviderPayment :one
UPDATE orders
SET provider_payment_id = $2
WHERE id = $1
RETURNING id, user_id, product_type, product_id, amount_cents, currency, provider, provider_payment_id, status, created_at, updated_at
`

type AttachProviderPaymentParams struct {
	ID                uuid.UUID `json:"id"`
	ProviderPaymentID *string   `json:"provider_payment_id"`
}

// Vincula el pago externo apenas el provider lo emite (preference/intent).
func (q *Queries) AttachProviderPayment(ctx context.Context, arg AttachProviderPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, attachProviderPayment, arg.ID, arg.ProviderPaymentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductType,
		&i.ProductID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, product_type, product_id, amount_cents, currency, provider)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, product_type, product_id, amount_cents, currency, provider, provider_payment_id, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ProductType string    `json:"product_type"`
	ProductID   uuid.UUID `json:"product_id"`
	AmountCents int32     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Provider    string    `json:"provider"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.ProductType,
		arg.ProductID,
		arg.AmountCents,
		arg.Currency,
		arg.Provider,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductType,
		&i.ProductID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, product_type, product_id, amount_cents, currency, provider, provider_payment_id, status, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductType,
		&i.ProductID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, user_id, product_type, product_id, amount_cents, currency, provider, provider_payment_id, status, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserOrders(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductType,
			&i.ProductID,
			&i.AmountCents,
			&i.Currency,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
