// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getContinueWatching = `-- name: GetContinueWatching :one
SELECT
  lp.lesson_id,
  lp.seconds,
  l.title      AS lesson_title,
  l.duration_s,
  m.title      AS module_title,
  m.position   AS module_position,
  c.id         AS course_id,
  c.slug       AS course_slug,
  c.title      AS course_title
FROM lesson_progress lp
JOIN lessons l ON l.id = lp.lesson_id
JOIN modules m ON m.id = l.module_id
JOIN courses c ON c.id = m.course_id
WHERE lp.user_id = $1 AND NOT lp.completed
ORDER BY lp.updated_at DESC
LIMIT 1
`

type GetContinueWatchingRow struct {
	LessonID       uuid.UUID `json:"lesson_id"`
	Seconds        int32     `json:"seconds"`
	LessonTitle    string    `json:"lesson_title"`
	DurationS      int32     `json:"duration_s"`
	ModuleTitle    string    `json:"module_title"`
	ModulePosition int32     `json:"module_position"`
	CourseID       uuid.UUID `json:"course_id"`
	CourseSlug     string    `json:"course_slug"`
	CourseTitle    string    `json:"course_title"`
}

// El hero del dashboard: la última lección tocada con contexto completo.
func (q *Queries) GetContinueWatching(ctx context.Context, userID uuid.UUID) (GetContinueWatchingRow, error) {
	row := q.db.QueryRow(ctx, getContinueWatching, userID)
	var i GetContinueWatchingRow
	err := row.Scan(
		&i.LessonID,
		&i.Seconds,
		&i.LessonTitle,
		&i.DurationS,
		&i.ModuleTitle,
		&i.ModulePosition,
		&i.CourseID,
		&i.CourseSlug,
		&i.CourseTitle,
	)
	return i, err
}

const listCourseProgressByUser = `-- name: ListCourseProgressByUser :many
SELECT user_id, course_id, completed_lessons, total_lessons, last_lesson_id, updated_at FROM course_progress
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListCourseProgressByUser(ctx context.Context, userID uuid.UUID) ([]CourseProgress, error) {
	rows, err := q.db.Query(ctx, listCourseProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseProgress
	for rows.Next() {
		var i CourseProgress
		if err := rows.Scan(
			&i.UserID,
			&i.CourseID,
			&i.CompletedLessons,
			&i.TotalLessons,
			&i.LastLessonID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLessonCompleted = `-- name: MarkLessonCompleted :one
INSERT INTO lesson_progress (user_id, lesson_id, seconds, completed, completed_at, updated_at)
VALUES ($1, $2, $3, true, now(), now())
ON CONFLICT (user_id, lesson_id) DO UPDATE SET
  seconds      = GREATEST(lesson_progress.seconds, EXCLUDED.seconds),
  completed    = true,
  completed_at = COALESCE(lesson_progress.completed_at, now()),
  updated_at   = now()
RETURNING user_id, lesson_id, seconds, completed, completed_at, updated_at
`

type MarkLessonCompletedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LessonID uuid.UUID `json:"lesson_id"`
	Seconds  int32     `json:"seconds"`
}

func (q *Queries) MarkLessonCompleted(ctx context.Context, arg MarkLessonCompletedParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, markLessonCompleted, arg.UserID, arg.LessonID, arg.Seconds)
	var i LessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonID,
		&i.Seconds,
		&i.Completed,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshCourseProgress = `-- name: RefreshCourseProgress :exec
INSERT INTO course_progress (user_id, course_id, completed_lessons, total_lessons, last_lesson_id, updated_at)
SELECT
  $1,
  $2,
  count(*) FILTER (WHERE lp.completed),
  count(*),
  (
    SELECT lp2.lesson_id
    FROM lesson_progress lp2
    JOIN lessons l2 ON l2.id = lp2.lesson_id
    JOIN modules m2 ON m2.id = l2.module_id
    WHERE lp2.user_id = $1 AND m2.course_id = $2
    ORDER BY lp2.updated_at DESC
    LIMIT 1
  ),
  now()
FROM lessons l
JOIN modules m ON m.id = l.module_id
LEFT JOIN lesson_progress lp
  ON lp.lesson_id = l.id AND lp.user_id = $1
WHERE m.course_id = $2
ON CONFLICT (user_id, course_id) DO UPDATE SET
  completed_lessons = EXCLUDED.completed_lessons,
  total_lessons     = EXCLUDED.total_lessons,
  last_lesson_id    = EXCLUDED.last_lesson_id,
  updated_at        = now()
`

type RefreshCourseProgressParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

// Recalcula el agregado de un curso para un usuario. Se llama tras
// MarkLessonCompleted; barato porque acota por curso.
func (q *Queries) RefreshCourseProgress(ctx context.Context, arg RefreshCourseProgressParams) error {
	_, err := q.db.Exec(ctx, refreshCourseProgress, arg.UserID, arg.CourseID)
	return err
}

const upsertHeartbeat = `-- name: UpsertHeartbeat :exec
INSERT INTO lesson_progress (user_id, lesson_id, seconds, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, lesson_id) DO UPDATE SET
  seconds    = GREATEST(lesson_progress.seconds, EXCLUDED.seconds),
  updated_at = now()
`

type UpsertHeartbeatParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LessonID uuid.UUID `json:"lesson_id"`
	Seconds  int32     `json:"seconds"`
}

// Un heartbeat del player cada ~15 s. GREATEST evita que un seek
// hacia atrás pise el máximo alcanzado; completed nunca retrocede.
func (q *Queries) UpsertHeartbeat(ctx context.Context, arg UpsertHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertHeartbeat, arg.UserID, arg.LessonID, arg.Seconds)
	return err
}
